baseURL = 'https://pensiveibex.com/'
languageCode = 'en-uk'
title = 'Pensive Ibex'
sectionPagesMenu = 'main'
pluralizelisttitles = 'false'
theme = 'hugo-bearcub'

[Params]
    [Params.Author]
        name = 'Luk Weyens'
        email = 'luk@pensiveibex.com'
        github = 'https://github.com/WeyensLuk/pensive-ibex'